### ISSUE TITLE
Empty layer definition duplicated

### ISSUE THREAD

**Issue by levrik** [vanilla-extract-css/vanilla-extract#1347]
### Describe the bug

Empty layer definitions not only get added for `globalLayer(...)` but also when using them inside `style(...)`.

At first I thought that this will change the order of layers but after refreshing my knowledge only the first occurence defines the order so that's okay. Still this behavior is unexpected and I would only expect the empty declarations to be created by `globalLayer(...)` and not implicitly by `style(...)` as well.

It does not happen when `globalLayer(...)` and the usage of the layer inside `style(...)` are in the same file.

### Reproduction

https://codesandbox.io/p/devbox/funny-shtern-95ykmj?file=%2Fdist%2Fmain.css&workspaceId=cf852eb1-d673-4ef5-b3db-9b4a4bbf8155

### System Info

```shell
System:
  OS: macOS 13.6.4
  CPU: (8) arm64 Apple M1 Pro
  Memory: 65.86 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
  pnpm: 8.15.4 - ~/Library/pnpm/pnpm
Browsers:
  Safari: 17.3.1
npmPackages:
  @vanilla-extract/css: 1.14.1 => 1.14.1 
  @vanilla-extract/recipes: 0.5.1 => 0.5.1 
  @vanilla-extract/webpack-plugin: 2.3.6 => 2.3.6
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@levrik This is intentional behaviour.

We create empty `@layer` definitions for `style` calls in order to hoist them to the top of the output CSS. This ensures consistent ordering of layers, i.e. they are declared in the order they're first referenced in a `.css.ts` file. See [the docs](https://vanilla-extract.style/documentation/api/layer/#layer-merging) for an example.

Within a single file, duplicate empty `@layer` definitions can be removed. However, across separate files this isn't possible since `.css.ts` files are evaluated in isolation from eachother.

We initially tried to implement some logic that would go even further and remove the empty `@layer` definitions if possible, but it ended up being harder than we though, so we opted to go with a simpler hoisting implementation that has the downside of generating slightly more verbose CSS.

IMO this isn't really a concern as I would assume that CSS minifiers can remove these duplicate `@layer` definitions easily (at least within a single `.css` file). While it would be nice if VE generated slightly more concise CSS in this case, it's not really a focus right now.

**Comment by levrik** [comment]
@askoufis Thanks a lot for the detailed answer. Maybe some information around it could be added to the documentation as at first I thought that something was broken. I'll also check if minimizers actually remove the duplicates or not. I'm curious now.
