### ISSUE TITLE
Vite: is there a way to import files in `.css.ts` files?

### ISSUE THREAD

**Issue by dkzlv** [vanilla-extract-css/vanilla-extract#665]
Currently importing an image fails with this error:

```
[plugin:vanilla-extract] Build failed with 1 error:
Check.css.ts:6:16: error: No loader is configured for ".png" files: pic.png
```

, even though it works fine in a regular `.ts` file.

**Comment by wobsoriano** [comment]
`.css.ts` is working fine on my end with latest vite version. Try

```ts
export default defineConfig({
  assetsInclude: ['**/*.png'],
  ...
})
```

**Comment by AndrewLeedham** [comment]
This is probably because [Vanilla Extract runs `.css.ts` files in esbuild](https://github.com/seek-oss/vanilla-extract/blob/master/packages/integration/src/compile.ts#L45) to generate the stylesheets, regardless of which plugin you use. There is currently no way to add loaders or configure esbuild here. Curious what your use case is?

**Comment by AndrewLeedham** [comment]
@dkzlv Makes sense. I think having the ability to configure esbuild would be a good addition, it would also be a better way of doing this: https://github.com/seek-oss/vanilla-extract/pull/661

**Comment by graup** [comment]
I believe this is also a problem with importing font files (.woff2) in your VE files. Maybe we can consider adding support for url imports (images, font files) to the default config.

**Comment by willbattel** [comment]
Yeah I'm trying use static assets in my CSS, such as for a custom `<li>` bullet style, but we're facing the same limitation.

```
import { style } from "@vanilla-extract/css";

import myIcon from '../assets/icons/MyIcon.svg'

export const myListItem = style({
    listStyle: `url(${myIcon})`,
})
```

```
[plugin:vanilla-extract] Build failed with 1 error:
src/components/MyComponent.css.ts:6:25: error: No loader is configured for ".svg" files: src/assets/icons/MyIcon.svg
```

Is this something we can get working with some tweaking of esbuild?

**Comment by johanneslumpe** [comment]
Is there something the community can help with here? It's not possible to use a file loader right now because it requires defining the `outDir` for esbuild, which isn't exposed in the current esbuild options.

**Comment by wobsoriano** [comment]
For now, I am manually setting esbuild loader object

```ts
// vite.config.ts
import react from '@vitejs/plugin-react'
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';

export default defineConfig({
  plugins: [
    vanillaExtractPlugin({
      esbuildOptions: {
        loader: {
          '.png': 'dataurl', // 'base64' | 'file' | 'dataurl' | 'binary' | 'default' | 'js' | 'jsx' | 'ts' | 'tsx' | 'css' | 'json' | 'text'
        }
      }
    }),
    react()
  ],
})
```

```ts
import { style } from '@vanilla-extract/css';
import Pic from './pic.png';

export const root = style({
  backgroundImage: `url(${Pic})`,
});
```

Or via a plugin

```ts
import react from '@vitejs/plugin-react'
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';

export default defineConfig({
  plugins: [
    vanillaExtractPlugin({
      esbuildOptions: {
        plugins: [ExportImageAsJS()]
      }
    }),
    react()
  ],
})

export function ExportImageAsJS() {
  const plugin = {
      name: 'image-to-js',
      setup(build) {
          build.onLoad({
              filter: /\.png$/
          }, async (args) => {
              return {
                  contents: `
                    const file = "${args.path.replace(build.initialOptions.absWorkingDir, '')}"
                    export default file
                  `,
                  loader: 'js',
              };
          });
      },
  };

  return plugin;
}
```

**Comment by wobsoriano** [comment]
Made a simple plugin that fixes this

https://github.com/wobsoriano/esbuild-vanilla-image-loader

```js
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin'
import { ImageLoader } from 'esbuild-vanilla-image-loader'

export default defineConfig({
  plugins: [
    vanillaExtractPlugin({
      esbuildOptions: {
        plugins: [ImageLoader()],
      }
    }),
  ],
})
```

**Comment by MananTank** [comment]
@wobsoriano Works perfectly! Awesome job

**Comment by viridia** [comment]
I ran into this same issue as well (using Vite) - I have a bunch of custom cursors (pngs). What I ended up doing is putting all the cursors in their own stylesheet that uses CSS modules rather than vanilla extract. It's an ugly hack but at least I'm unblocked.

I tried the plugin and couldn't get it to work - the url that it produced had the wrong path.

**Comment by yume-chan** [comment]
I'm using Solid-Start, If I directly write relative paths in `url()`, it's not handled by vanilla-extract, but will be handled by vite itself! (I guess when vanilla-extract gives the generated CSS to vite)

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/1330321/02ac4471-f2d5-4e84-afc0-d33c877fd267)

Run `npm run build`:

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/1330321/32c58e90-3b3e-4c26-9629-1cf50c4e4391)

The issue is that vanilla-extract inserts a wrong style sheet in development mode:

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/1330321/fa50e9f4-f900-492d-a733-2a8b3929cd6c)

It overrides the correct property below

**Comment by askoufis** [comment]
@dkzlv This issues seems solved by the addition of `esbuildOptions` to the esbuild, vite and rollup plugins. The docs were missing for vite and rollup, but I've added that in #1120.

**Comment by ksandin** [comment]
Why would we not want this to be dealt with automatically in all vanilla extract integrations? Referencing assets from css files is a very normal workflow. Adding extra plugins just to support assets like svgs, images, font files, etc. is a pretty annoying extra overhead to have to deal with.

**Comment by ksandin** [comment]
I've thought about this issue some more, and I suggest re-opening this issue! Here's why:

First off, I do think it's a good idea for vanilla-extract to be abstracted away from the bundler of choice. The bundler is after all responsible for assets, since it's part of the bundling process, so expecting it to be handled out of the box is a bit unfair. However, we can't ignore the fact that it's incredibly common to reference things like images and fonts in css files, and since `.css.ts` files are supposed to simply be a typesafe variant of css files, why should that workflow not also be possible, and  typesafe? 

I see two things missing: A: documentation, B: integration configuration options

## Documentation

Nowhere in the docs is there any mention of the limitations explored in this github issue. There's even no information on how to simply import assets in `.css.ts` files, which I think is very surprising considering how common of a workflow that is. 

At the very least I would expect a section in the docs explaining this caveat so it's more visible to new users, and even better provide some examples on how you can implement asset support in `.css.ts files`, preferably one example per integration.

## Integration configuration options

As mentioned in this thread, [esbuildOptions](https://vanilla-extract.style/documentation/integrations/esbuild/#esbuildoptions) allow us to extend esbuild to support asset imports, even if it requires some [heavy tinkering](https://github.com/ksandin/yas/blob/e394d8997d1592b6595462c5a432af03097ce5b4/tools/esbuild-file-url-plugin/src/index.js). The problem is this isn't consistent across all integrations. I've tried to do the same thing with webpack, but was not able to because some configuration options are missing. I don't know about the rest of our integrations. I think this kind of caveat would also be worth mentioning in the docs, but more importantly it begs the question, do we not want to improve this? I think it would be great if we could make each vanilla-extract integration configurable enough to support importing assets, preferably even adding test cases to ensure this common workflow is possible in all integrations.
