### ISSUE TITLE
@vanilla-extract/vite-plugin doesn't work with monorepo aliases

### ISSUE THREAD

**Issue by mc-petry** [vanilla-extract-css/vanilla-extract#749]
### Describe the bug

Monorepo setup:
app
|- @pkg/a
|- @pkg/b

`@pkg/a` contains sprinkles.
`@pkg/b` depends on `@pkg/a` and using sprinkles from it.

Application is vite based using `@vanilla-extract/vite-plugin`:

```tsx
export default defineConfig(async ({ command }) => {
  return {
    plugins: [react(), vanillaExtractPlugin()],
    resolve: {
      alias: [
        {
          // Resolve local packages
          find: /^@pkg\/(.+)$/,
          replacement: `${path.resolve(
            __dirname,
            "../../packages"
          )}/$1/src/index.ts`,
        },
      ],
    },
  };
});
```

This solution works fine without using vanilla-extract.

How to see a bug:
1) pnpm i
2) pnpm dev
At this step site works
3) go to `packages/b/src/button.tsx` and uncomment styles

### Reproduction

https://github.com/mc-petry/vanilla-extract-monorepo

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @vanilla-extract/css: ^1.7.2 => 1.7.2 
    @vanilla-extract/css-utils: ^0.1.2 => 0.1.2 
    @vanilla-extract/esbuild-plugin: ^2.1.0 => 2.1.0 
    @vanilla-extract/private: ^1.0.3 => 1.0.3 
    @vanilla-extract/recipes: ^0.2.5 => 0.2.5 
    @vanilla-extract/sprinkles: ^1.4.1 => 1.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ochomoswill** [comment]
You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go

You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go
You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go
You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go

**Comment by ochomoswill** [comment]
You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go


You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go


You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go


You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go

You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go

You can retrieve virtual card details via the Dashboard or via the API. [PCI-DSS](https://stripe.com/guides/pci-compliance) rules protect cardholder data. For PCI-DSS compliance, we recommend limiting retrieval of virtual card information to the dashboard. If the API is used to retrieve card information, or if virtual card information is exported from the Dashboard, the information should be stored in a password manager or otherwise encrypted.

You can retrieve both the full unredacted card number and CVC from the API. For security reasons, you can only use these fields with virtual cards in live mode, and we omit them unless you explicitly request them with the [expand](https://stripe.com/docs/api/expanding_objects) property. You can only retrieve these fields for physical cards in [test mode](https://stripe.com/docs/keys#test-live-modes). Additionally, you can only access them through the [Retrieve a card](https://stripe.com/docs/api/issuing/cards/retrieve) endpoint.


curl

Stripe CLI

Ruby

Python

PHP

Java

Node

Go

**Comment by sina-salahshour** [comment]
hi. i'm trying to use vanilla extract with sveltekit. the the `paths` and `rootDirs` fields are defined by sveltekit itself and works well on other ts files. but doesn't work with .css.ts files. it works when i change the imports to relative import.


i used the vite plugin to install this library

**Comment by askoufis** [comment]
> hi. i'm trying to use vanilla extract with sveltekit. the the `paths` and `rootDirs` fields are defined by sveltekit itself and works well on other ts files. but doesn't work with .css.ts files. it works when i change the imports to relative import.
> 
> i used the vite plugin to install this library

@sina-salahshour You might need the [`vite-tsconfig-paths`](https://www.npmjs.com/package/vite-tsconfig-paths) plugin to get this to work. If that doesn't work, please raise a separate issue with a minimal reproduction.
